RECORD_TYPE_WORKLOG = "worklog"
RECORD_TYPE_SEGMENT = "segment"
RECORD_TYPE_ADJUSTMENT = "adjustment"
RECORD_TYPE_REMITTANCE = "remittance"
RECORD_TYPE_SETTLEMENT_LINE = "settlement_line"

REMITTANCE_STATUS_PENDING = "PENDING"
REMITTANCE_STATUS_COMPLETED = "COMPLETED"
REMITTANCE_STATUS_FAILED = "FAILED"
REMITTANCE_STATUS_CANCELLED = "CANCELLED"

REMITTANCE_ACTIVE_STATUSES = [
    REMITTANCE_STATUS_PENDING,
    REMITTANCE_STATUS_COMPLETED,
]

FILTER_REMITTED = "REMITTED"
FILTER_UNREMITTED = "UNREMITTED"
